name: Build & Deploy to Itch.io
on:
  push:
    tags:
      - v*
jobs:
  tag:
    name: New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Zip Distribution
        run: zip -r dist.zip dist

      - name: Deploy to Itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          VERSION: ${{ env.RELEASE_VERSION }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          PACKAGE: dist.zip
          CHANNEL: web
